<a href="https://colab.research.google.com/github/SiracencoSerghei/linear_algebra/blob/main/3.1_eigen_decomposition/3.1_8_eigen-Layers_code_challenge.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sympy import *
from mpl_toolkits.mplot3d import Axes3D

---
# Code Challenge: reconstruct a matrix from eigenLayers
---

In [11]:
# create an mxm symmetric matrix (5x5), take eigenDecompos.
m = 5
A = np.random.randn(m,m)
A = np.round(10*A.T@A)

D,V = np.linalg.eig(A)

# convert to column vector
v = V[:,2]
print(v)
print(v.T)
print(np.reshape(v,(m,1)))
print(np.reshape(v,(m,1)).T)


[ 0.45896223  0.24145472 -0.2467695   0.17676273 -0.79932036]
[ 0.45896223  0.24145472 -0.2467695   0.17676273 -0.79932036]
[[ 0.45896223]
 [ 0.24145472]
 [-0.2467695 ]
 [ 0.17676273]
 [-0.79932036]]
[[ 0.45896223  0.24145472 -0.2467695   0.17676273 -0.79932036]]


In [13]:
# show that the norm of the outer product of v_i = 1
op = np.outer(v,v)
print(op), print(' ')

v = np.reshape(V[:,2],(m,1))
print(v), print(' ')
print(v*v.T), print(' ') # with orientation can use *
print(v@v.T), print(' ')

print( np.linalg.norm(op) )


[[ 0.21064633  0.1108186  -0.11325788  0.08112742 -0.36685786]
 [ 0.1108186   0.05830038 -0.05958366  0.0426802  -0.19299967]
 [-0.11325788 -0.05958366  0.06089519 -0.04361965  0.19724789]
 [ 0.08112742  0.0426802  -0.04361965  0.03124506 -0.14129005]
 [-0.36685786 -0.19299967  0.19724789 -0.14129005  0.63891303]]
 
[[ 0.45896223]
 [ 0.24145472]
 [-0.2467695 ]
 [ 0.17676273]
 [-0.79932036]]
 
[[ 0.21064633  0.1108186  -0.11325788  0.08112742 -0.36685786]
 [ 0.1108186   0.05830038 -0.05958366  0.0426802  -0.19299967]
 [-0.11325788 -0.05958366  0.06089519 -0.04361965  0.19724789]
 [ 0.08112742  0.0426802  -0.04361965  0.03124506 -0.14129005]
 [-0.36685786 -0.19299967  0.19724789 -0.14129005  0.63891303]]
 
[[ 0.21064633  0.1108186  -0.11325788  0.08112742 -0.36685786]
 [ 0.1108186   0.05830038 -0.05958366  0.0426802  -0.19299967]
 [-0.11325788 -0.05958366  0.06089519 -0.04361965  0.19724789]
 [ 0.08112742  0.0426802  -0.04361965  0.03124506 -0.14129005]
 [-0.36685786 -0.19299967  0.19724

In [15]:
# create one Layer of A as lvv', compute its norm
print(v*D[2]*v.T)
print( np.linalg.norm(v*D[2]*v.T) )
print(D[2])

[[  8.42178914   4.43060582  -4.52813018   3.24353151 -14.66723628]
 [  4.43060582   2.33089046  -2.38219689   1.7063844   -7.7162633 ]
 [ -4.52813018  -2.38219689   2.43463266  -1.74394451   7.88610996]
 [  3.24353151   1.7063844   -1.74394451   1.24919972  -5.64887606]
 [-14.66723628  -7.7162633    7.88610996  -5.64887606  25.54419454]]
39.98070652166003
39.98070652166003


In [19]:
# reconstruct A by summer over outer products
Arecon = np.zeros((m,m))

for i in range(m):
  v = np.reshape(V[:,i],(m,1))
  Arecon += v*D[i]*v.T
  print(np.linalg.matrix_rank(Arecon))

print(' ')
print(A), print(' ')
print(Arecon), print(' ')
print(np.round((A-Arecon),3)), print(' ')


1
2
3
4
5
 
[[ 44.  25.  32. -18.  -4.]
 [ 25.  26.  16. -28.  -1.]
 [ 32.  16.  49. -20.  16.]
 [-18. -28. -20.  88.  -2.]
 [ -4.  -1.  16.  -2.  32.]]
 
[[ 44.  25.  32. -18.  -4.]
 [ 25.  26.  16. -28.  -1.]
 [ 32.  16.  49. -20.  16.]
 [-18. -28. -20.  88.  -2.]
 [ -4.  -1.  16.  -2.  32.]]
 
[[ 0.  0. -0.  0. -0.]
 [ 0.  0.  0. -0.  0.]
 [-0.  0.  0.  0.  0.]
 [ 0. -0.  0.  0. -0.]
 [-0.  0.  0. -0. -0.]]
 


(None, None)

---
# Code Challenge: trace and determinant, eigenValues sum and product
---

In [21]:
#  trace(A) = sum(evals)
# det(A) = prod(evals)

A = np.random.randn(7,7)
tr = np.matrix.trace(A)
dt = np.linalg.det(A)
l = np.linalg.eig(A)[0]

print(tr,sum(l))
print(dt,np.prod(l))

-0.4015943816442239 (-0.401594381644212+0j)
-45.1512299057327 (-45.15122990573243+0j)


In [23]:
A = np.random.randn(7,5) @ np.random.randn(5,7)
tr = np.matrix.trace(A)
dt = np.linalg.det(A)
l = np.linalg.eig(A)[0]

print(tr,sum(l))
print(dt,np.prod(l))

3.644124504953827 (3.644124504953827+0j)
7.949362508530584e-29 (-1.772215584818576e-27+0j)
