In [1]:
import numpy as np
import matplotlib.pyplot as plt
import math

---
# VIDEO: Order-of-operations on matrices
---

The @ symbol in Python is used as the matrix multiplication operator.
 can use the @ operator instead of calling a function like np.dot() or np.matmul().

In [6]:

n = 3
L = np.random.randn(n,n)
I = np.random.randn(n,n)
V = np.random.randn(n,n)
E = np.random.randn(n,n)

# result of "forward" multiplication and then transpose
res1 = np.matrix.transpose( L @ I @ V @ E )
print(res1), print(' ')

# result of "flipped" multiplication of transposed matrices
res2 = E.T @ V.T @ I.T @ L.T
print(res2), print(' ')

# test equality by subtracting (ignore possible computer rounding errors)
print(res1-res2)


[[ 3.45793891 -0.83803562  3.3243401 ]
 [-1.91708735  0.58029613 -2.43825969]
 [ 3.7253381  -0.79081447  4.15242358]]
 
[[ 3.45793891 -0.83803562  3.3243401 ]
 [-1.91708735  0.58029613 -2.43825969]
 [ 3.7253381  -0.79081447  4.15242358]]
 
[[ 3.45793891 -0.83803562  3.3243401 ]
 [-1.91708735  0.58029613 -2.43825969]
 [ 3.7253381  -0.79081447  4.15242358]]
 
[[ 4.44089210e-16 -1.11022302e-16 -4.44089210e-16]
 [ 4.44089210e-16  0.00000000e+00 -4.44089210e-16]
 [ 4.44089210e-16  0.00000000e+00  0.00000000e+00]]
