In [1]:
import numpy as np
import matplotlib.pyplot as plt
import math

---
# Element-wise (Hadamard) multiplication
---

In [2]:
# any matrix sizes
m = 13
n =  2

# ...but the two matrices must be the same size
A = np.random.randn(m,n)
B = np.random.randn(m,n)

# note the different syntax compared to @ for matrix multiplication
C1 = np.multiply( A,B )
C2 = A*B

print(C1), print(' ')
print(C2), print(' ')

print(C1-C2)

[[-0.44714554 -1.38528319]
 [-0.22876156  1.829303  ]
 [ 0.26803189  0.51179173]
 [ 0.01962091 -0.74819179]
 [-0.16812217 -0.02076405]
 [-0.73052752 -0.08713701]
 [-1.30459365  0.60543887]
 [-0.39235646 -0.28997717]
 [-0.70800808 -0.33281745]
 [ 0.02812896  0.11157486]
 [-0.19050087  0.12473615]
 [ 0.15101756  0.16551165]
 [ 1.32607576 -0.63211084]]
 
[[-0.44714554 -1.38528319]
 [-0.22876156  1.829303  ]
 [ 0.26803189  0.51179173]
 [ 0.01962091 -0.74819179]
 [-0.16812217 -0.02076405]
 [-0.73052752 -0.08713701]
 [-1.30459365  0.60543887]
 [-0.39235646 -0.28997717]
 [-0.70800808 -0.33281745]
 [ 0.02812896  0.11157486]
 [-0.19050087  0.12473615]
 [ 0.15101756  0.16551165]
 [ 1.32607576 -0.63211084]]
 
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
