In [2]:
import numpy as np
import matplotlib.pyplot as plt
import math

---
# standart matrix multiplication
---

In [11]:
# rules for standart matrix multiplication

m = 4
n = 3
k = 6

# make some matrices
A = np.random.randn(m,n)
B = np.random.randn(n,k)
C = np.random.randn(m,k)

# test which miltiplication are valid.
# Think of your answer first, then test.
print(np.matmul(A,B))
# np.matmul(A,A)
print(np.matmul(A.T,C))
print(np.matmul(B,B.T))
print(np.matmul(np.matrix.transpose(B),B))
# np.matmul(B,C)
# np.matmul(C,B)
# np.matmul(C.T,B)
print(np.matmul(C,B.T))


[[ 0.71355431  1.74407763  1.17287162 -0.55660515  0.11438732 -1.21793063]
 [ 3.85320599 -2.40925934  1.04022506  1.57975753  0.74441652  0.47696393]
 [ 1.150514   -0.87607512  0.75498386  1.3840475  -0.11847501 -0.63874468]
 [ 1.34379235 -1.80596225  1.02464091  2.7362076  -0.45818104 -1.11749285]]
[[-0.15709716 -1.83072215 -0.31345593  3.80346016  1.06146306  2.58642975]
 [-0.75535585 -0.07147601 -0.5783461   2.0558215   0.12082978 -0.61067438]
 [-0.24031096  0.05252361 -0.27572646 -0.4988078   0.68770478  2.13282125]]
[[ 2.80779353 -0.21437298  1.24756127]
 [-0.21437298  2.23149148  2.41601078]
 [ 1.24756127  2.41601078  6.78923791]]
[[ 2.51295302 -0.65445447  1.07637125  0.65439788  0.48388132 -0.21472865]
 [-0.65445447  1.31702543 -0.58031887 -1.9608293   0.40286935  0.75434971]
 [ 1.07637125 -0.58031887  1.06441532  1.61749643 -0.28044247 -1.16694563]
 [ 0.65439788 -1.9608293   1.61749643  4.40404409 -1.2780326  -2.62328376]
 [ 0.48388132  0.40286935 -0.28044247 -1.2780326   0.56

In [21]:
# generate two matrices

m = 3
n = 2

A = np.random.randn(m,n)
B = np.random.randn(n,m)

print(A), print(' ')
print(B), print(' ')
# build the product matrix 
C1 = np.zeros((m,m))
C1_1 = C1
for i in range(n):
    C1_1 += np.outer(A[:,i],B[i,:])

C1_2 = C1
for i in range(m):
    for j in range(m):
        C1_2[i, j] = sum(A[i, k] * B[k, j] for k in range(n))

print(C1_1), print(' ')
print(C1_2), print(' ')

# implement matrix multiplication
C2 = A@B
print(C2), print(' ')
# C2 = np.dot(A, B)
# print(C2), print(' ')
C2 = np.matmul(A, B)
print(C2), print(' ')

# compare the results
result = C1 - C2
print(result)


[[ 0.44757713 -0.10789144]
 [-0.78383771 -1.44573266]
 [-0.71634616 -0.03521881]]
 
[[ 1.62503424 -0.8935697   1.95846783]
 [ 0.2929852   0.67070742 -0.1274118 ]]
 
[[ 0.69571756 -0.47230495  0.89031205]
 [-1.69734139 -0.26925    -1.35091753]
 [-1.17440562  0.61648371 -1.39845361]]
 
[[ 0.69571756 -0.47230495  0.89031205]
 [-1.69734139 -0.26925    -1.35091753]
 [-1.17440562  0.61648371 -1.39845361]]
 
[[ 0.69571756 -0.47230495  0.89031205]
 [-1.69734139 -0.26925    -1.35091753]
 [-1.17440562  0.61648371 -1.39845361]]
 
[[ 0.69571756 -0.47230495  0.89031205]
 [-1.69734139 -0.26925    -1.35091753]
 [-1.17440562  0.61648371 -1.39845361]]
 
[[0.00000000e+00 5.55111512e-17 0.00000000e+00]
 [2.22044605e-16 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00]]
