In [1]:
import numpy as np

---
# Matrix-vector multiplication
---

In [10]:

# number of elements
m = 4

# create matrices
N = np.random.randint(-10,11,(m,m))
S = np.round( N.T*N / m**2 ) # scaled symmetric

# and a column vector
w = np.array([[-1, 0, 1, 2]]).T
print(w), print(' ')

# with symmetric matrix
print('with symmetric matrix')
print( S@w ), print(' ')     # 1
print( S.T@w ), print(' ')   # 2
# print( w@S ), print(' ')     # 3 
# signature (n?,k),(k,m?)->(n?,m?) (size 4 is different from 1)
print( w.T@S.T ), print(' ') # 4
print( w.T@S ), print(' ')   # 5

# with nonsymmetric matrix
print('with nonsymmetric matrix')
print( N@w ), print(' ')     # 1
print( N.T@w ), print(' ')   # 2
# print( w@N ), print(' ')     # 3
# signature (n?,k),(k,m?)->(n?,m?) (size 4 is different from 1)
print( w.T@N.T ), print(' ') # 4
print( w.T@N ), print(' ')   # 5

[[-1]
 [ 0]
 [ 1]
 [ 2]]
 
with symmetric matrix
[[ 0.]
 [ 0.]
 [ 1.]
 [-3.]]
 
[[ 0.]
 [ 0.]
 [ 1.]
 [-3.]]
 
[[ 0.  0.  1. -3.]]
 
[[ 0.  0.  1. -3.]]
 
with nonsymmetric matrix
[[ 17]
 [ -8]
 [-15]
 [  4]]
 
[[ 28]
 [-21]
 [ 18]
 [ -7]]
 
[[ 17  -8 -15   4]]
 
[[ 28 -21  18  -7]]
 


(None, None)