<a href="https://colab.research.google.com/github/SiracencoSerghei/linear_algebra/blob/main/2.2_matrixMultiplication/2_2_7_symmetry_of_combined_symm_matrices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:

import numpy as np

---
# Code challenge: symmetry of combined symmetric matrices
---

In [ ]:
# create two symmetric matrices
m = 3
A = np.random.randn(m,m)
AtA = A.T@A

B = np.random.randn(m,m)
BtB = B.T@B

# compute sum, multiplication and Hadamard multiplication
Cs = AtA + BtB # sum
Cm = AtA @ BtB # multiplication
Ch = AtA * BtB # Hadamard

# determine whether result is symmetric
print( Cs - Cs.T ), print(' ')
print( Cm - Cm.T ), print(' ')
print( Ch - Ch.T )

# Symmetry is confirmed when the difference between
# a matrix and its transpose results in a zero matrix.


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
 
[[ 0.         -2.50459886 -2.0884398 ]
 [ 2.50459886  0.          0.73503592]
 [ 2.0884398  -0.73503592  0.        ]]
 
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


---
# VIDEO: Multiplication of two symmetric matrices
---

In [ ]:
# using the sympy library
from sympy import *

a,b,c,d,e,f,g,h,k,l,m,n,o,p,q,r,s,t,u = symbols('a b c d e f g h k l m n o p q r s t u', real=True)

# symmetric and constant-diagonal matrices
A = Matrix([ [a,b,c,d],
             [b,a,e,f],
             [c,e,a,h],
             [d,f,h,a]   ])

B = Matrix([ [l,m,n,o],
             [m,l,q,r],
             [n,q,l,t],
             [o,r,t,l]   ])


# confirmation that A and B are symmetric
print( A - A.transpose() )
print( B - B.transpose() )

# ... and constant diagonal
for i in range(0,np.size(A,0)):
    print( A[i,i] )
for i in range(0,np.size(B,0)):
    print( B[i,i] )


Matrix([[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]])
Matrix([[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]])
a
a
a
a
l
l
l
l


In [ ]:
# nice printing in sympy
init_printing()

# but AB neq (AB)'
A@B - (A@B).T

# maybe for a submatrix?
n = 3
A1 = A[ 0:n,0:n ]
B1 = B[ 0:n,0:n ]

A1@B1 - (A1@B1).T


⎡    0       c⋅q - e⋅n   b⋅q - e⋅m⎤
⎢                                 ⎥
⎢-c⋅q + e⋅n      0       b⋅n - c⋅m⎥
⎢                                 ⎥
⎣-b⋅q + e⋅m  -b⋅n + c⋅m      0    ⎦

---
# Code challenge: Standart and Hadamard multiplication for diagonal matricies
---

In [3]:
# create two square matricies: "full" and diagonal
A = np.random.randn(4,4)
D = np.diag(np.random.randn(4))

# multiply each matrix by itself: Standard and Hadamard
print( A@A ), print(' ')
print( A*A ), print(' ')

print( D@D ), print(' ')
print( D*D ), print(' ')


[[ 0.51906288 -2.52607708 -0.07609177 -3.17005461]
 [-0.65498579  1.1861511  -0.30567311 -2.77260865]
 [ 1.76289449 -3.19127747 -2.13564835  0.07558093]
 [-1.22817391 -1.74978847  0.30610125  2.70053692]]
 
[[2.03996060e+00 3.01263774e+00 1.29460569e+00 4.88217741e-04]
 [9.02236147e-02 2.15496787e-02 3.54160010e-01 2.81799897e+00]
 [3.25513272e+00 7.54075600e-02 2.16475909e-01 5.08291499e-02]
 [2.29180937e-01 2.30912745e-01 3.63206099e-01 2.01916491e+00]]
 
[[0.15307722 0.         0.         0.        ]
 [0.         0.6001987  0.         0.        ]
 [0.         0.         0.23847665 0.        ]
 [0.         0.         0.         0.7516784 ]]
 
[[0.15307722 0.         0.         0.        ]
 [0.         0.6001987  0.         0.        ]
 [0.         0.         0.23847665 0.        ]
 [0.         0.         0.         0.7516784 ]]
 


(None, None)