In [1]:

import numpy as np

---
# Code challenge: symmetry of combined symmetric matrices
---

In [5]:
# create two symmetric matrices
m = 3
A = np.random.randn(m,m)
AtA = A.T@A

B = np.random.randn(m,m)
BtB = B.T@B

# compute sum, multiplication and Hadamard multiplication
Cs = AtA + BtB # sum
Cm = AtA @ BtB # multiplication
Ch = AtA * BtB # Hadamard

# determine whether result is symmetric
print( Cs - Cs.T ), print(' ')
print( Cm - Cm.T ), print(' ')
print( Ch - Ch.T )

# Symmetry is confirmed when the difference between 
# a matrix and its transpose results in a zero matrix.


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
 
[[  0.         -14.24800267   0.74771775]
 [ 14.24800267   0.           2.31257749]
 [ -0.74771775  -2.31257749   0.        ]]
 
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


---
# VIDEO: Multiplication of two symmetric matrices
---

In [6]:
# using the sympy library
from sympy import *

a,b,c,d,e,f,g,h,k,l,m,n,o,p,q,r,s,t,u = symbols('a b c d e f g h k l m n o p q r s t u', real=True)

# symmetric and constant-diagonal matrices
A = Matrix([ [a,b,c,d],
             [b,a,e,f],
             [c,e,a,h],
             [d,f,h,a]   ])

B = Matrix([ [l,m,n,o],
             [m,l,q,r],
             [n,q,l,t],
             [o,r,t,l]   ])


# confirmation that A and B are symmetric
print( A - A.transpose() )
print( B - B.transpose() )

# ... and constant diagonal
for i in range(0,np.size(A,0)):
    print( A[i,i] )
for i in range(0,np.size(B,0)):
    print( B[i,i] )


ModuleNotFoundError: No module named 'sympy'

In [ ]:
# nice printing in sympy
init_printing()

# but AB neq (AB)'
A@B - (A@B).T

# maybe for a submatrix?
n = 3
A1 = A[ 0:n,0:n ]
B1 = B[ 0:n,0:n ]

# A1@B1 - (A1@B1).T
