In [1]:
import numpy as np


---
# 1
---

In [9]:

# Step 1: Create a column vector v
v = np.array([[1, 2, 3, 4]]).T
# v is a column vector with elements [1, 2, 3, 4]

print("Vector v:")
print(v)
print(' ')

# Step 2: Create the matrix S by stacking two row vectors and transposing the result
S = np.vstack(([4, 3, 6, 2], [0, 4, 0, 1])).T
# S is a 4x2 matrix with column vectors [4, 0], [3, 4], [6, 0], and [2, 1]

# Step 2: Create the matrix T by stacking two row vectors and transposing the result
T = np.vstack(([1, 2, 2, 2], [0, 0, 1, 2])).T
# T is a 4x2 matrix with column vectors [1, 0], [2, 0], [2, 1], and [2, 2]

print("Matrix S:")
print(S)
print(' ')

print("Matrix T:")
print(T)
print(' ')

# Step 3: Augment matrix S with the vector v by adding v as an additional column
Sv = np.concatenate((S, v), axis=1)
# Sv is a 4x3 matrix, where v is added as the third column to S

# Step 3: Augment matrix T with the vector v by adding v as an additional column
Tv = np.concatenate((T, v), axis=1)
# Tv is a 4x3 matrix, where v is added as the third column to T

print("Augmented Matrix Sv (S with v):")
print(Sv)
print(' ')

print("Augmented Matrix Tv (T with v):")
print(Tv)
print(' ')

# Step 4: Calculate the rank of the augmented matrix Sv
rank_Sv = np.linalg.matrix_rank(Sv)
print("Rank of Sv:", rank_Sv)
# If rank_Sv is equal to the rank of S (which is 2), v is in the span of S
# If rank_Sv is greater than 2, v is not in the span of S

# Step 4: Calculate the rank of the augmented matrix Tv
rank_Tv = np.linalg.matrix_rank(Tv)
print("Rank of Tv:", rank_Tv)
# If rank_Tv is equal to the rank of T (which is 2), v is in the span of T
# If rank_Tv is greater than 2, v is not in the span of T

Vector v:
[[1]
 [2]
 [3]
 [4]]
 
Matrix S:
[[4 0]
 [3 4]
 [6 0]
 [2 1]]
 
Matrix T:
[[1 0]
 [2 0]
 [2 1]
 [2 2]]
 
Augmented Matrix Sv (S with v):
[[4 0 1]
 [3 4 2]
 [6 0 3]
 [2 1 4]]
 
Augmented Matrix Tv (T with v):
[[1 0 1]
 [2 0 2]
 [2 1 3]
 [2 2 4]]
 
Rank of Sv: 3
Rank of Tv: 2
