In [1]:
import numpy as np
import matplotlib.pyplot as plt
import math

---
# Computing rank: theory and practice
---

In [6]:
# make a matrix
m = 4
n = 6

# create a random matrix
A = np.random.randn(m,n)

# what is the largest possible rank?
ra = np.linalg.matrix_rank(A)
print('rank = ' + str(ra))

# set last column to be repeat of penultimate column
B = A
print(B), print(' ')
B[:,-1] = B[:,-2]
print(B[:,-1])
print(B)

rb = np.linalg.matrix_rank(B)
print('rank = ' + str(rb))

rank = 4
[[ 0.10812734  0.15803734  0.69251414  0.3527542   1.04713556  0.38813995]
 [-0.0809294  -2.80006606  1.00232942 -1.46923597  0.95802992  1.39886138]
 [-0.93267014 -1.66483455 -0.61829851  0.55451961 -0.33844931  0.6459017 ]
 [ 0.78311619  0.08391396 -1.11133932 -0.38865726  0.95777427  0.12316616]]
 
[ 1.04713556  0.95802992 -0.33844931  0.95777427]
[[ 0.10812734  0.15803734  0.69251414  0.3527542   1.04713556  1.04713556]
 [-0.0809294  -2.80006606  1.00232942 -1.46923597  0.95802992  0.95802992]
 [-0.93267014 -1.66483455 -0.61829851  0.55451961 -0.33844931 -0.33844931]
 [ 0.78311619  0.08391396 -1.11133932 -0.38865726  0.95777427  0.95777427]]
rank = 4


In [7]:
## adding noise to a rank-deficient matrix

# square for convenience
A = np.round( 10*np.random.randn(m,m) )

# reduce the rank
A[:,-1] = A[:,-2]

# noise level
noiseamp = .001

# add the noise
B = A + noiseamp*np.random.randn(m,m)

print('rank (w/o noise) = ' + str(np.linalg.matrix_rank(A)))
print('rank (with noise) = ' + str(np.linalg.matrix_rank(B)))


rank (w/o noise) = 3
rank (with noise) = 4
