<a href="https://colab.research.google.com/github/SiracencoSerghei/linear_algebra/blob/main/3.2_SVD/3.2_6_inversePseudoInverse.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import matplotlib.pyplot as plt

---
# SVD, matrix inverse, and pseudoinverse
---

In [5]:
# the matrix
A = [ [1,2,3],
      [1,2,4], # hint: change 2->0 for invertible matrix to test
      [1,2,5]  ]

# A = [ [1,2,3],
#       [1,0,4], # hint: change 2->0 for invertible matrix to test
#       [1,2,5]  ]

# SVD
U,S,V = np.linalg.svd(A)
print(S), print(' ')

# pseudoinvert S
nonzeroels = S>10**-14 # find nonzero elements (>rounding errors)
S[nonzeroels] = 1/S[nonzeroels] # invert only those elements
print(S), print(' ')

# now pseudoinvert A
Ai = V.T@np.diag(S)@U.T

# it's sortof close to I...?
print( Ai@A ), print(' ')

# compute with pinv function
print( np.linalg.pinv(A)@A )

[8.03337644e+00 6.81808654e-01 8.88178420e-17]
 
[1.24480660e-01 1.46668716e+00 8.88178420e-17]
 
[[2.00000000e-01 4.00000000e-01 3.33066907e-16]
 [4.00000000e-01 8.00000000e-01 8.88178420e-16]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00]]
 
[[ 2.00000000e-01  4.00000000e-01  6.10622664e-16]
 [ 4.00000000e-01  8.00000000e-01  4.44089210e-16]
 [-5.55111512e-17 -1.11022302e-16  1.00000000e+00]]


In [4]:
import inspect
lines = inspect.getsource(np.linalg.pinv)
print(lines)

@array_function_dispatch(_pinv_dispatcher)
def pinv(a, rcond=1e-15, hermitian=False):
    """
    Compute the (Moore-Penrose) pseudo-inverse of a matrix.

    Calculate the generalized inverse of a matrix using its
    singular-value decomposition (SVD) and including all
    *large* singular values.

    .. versionchanged:: 1.14
       Can now operate on stacks of matrices

    Parameters
    ----------
    a : (..., M, N) array_like
        Matrix or stack of matrices to be pseudo-inverted.
    rcond : (...) array_like of float
        Cutoff for small singular values.
        Singular values less than or equal to
        ``rcond * largest_singular_value`` are set to zero.
        Broadcasts against the stack of matrices.
    hermitian : bool, optional
        If True, `a` is assumed to be Hermitian (symmetric if real-valued),
        enabling a more efficient method for finding singular values.
        Defaults to False.

        .. versionadded:: 1.17.0

    Returns
    -------
    