<a href="https://colab.research.google.com/github/SiracencoSerghei/linear_algebra/blob/main/3.2_SVD/3.2_2_SingularValsEigenVals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import matplotlib.pyplot as plt

---
# Relation between singular values and eigenvalues
---

In [2]:
# case 1: eig(A'A) vs. svd(A)

A = np.array([ [3,1,0], [1,1,0] ])

print( np.sort(np.linalg.eig(A.T@A)[0]) )
print( np.sort(np.linalg.svd(A)[1])**2 )

[ 0.          0.34314575 11.65685425]
[ 0.34314575 11.65685425]


In [3]:
# case 2: eig(A'A) vs. svd(A'A)

print(np.sort(np.linalg.eig(A.T@A)[0]))
print(np.sort(np.linalg.svd(A.T@A)[1]))

[ 0.          0.34314575 11.65685425]
[ 0.          0.34314575 11.65685425]


In [4]:
# case 3a: eig(A) vs. svd(A), real-valued eigs

# need a square matrix for eig
A = [ [3,1,0], [1,1,0], [1,1,1]]

print(np.sort(np.linalg.eig(A)[0]))
print(np.sort(np.linalg.svd(A)[1]))

[0.58578644 1.         3.41421356]
[0.49384652 1.10038368 3.68039011]


In [6]:
# case 3b: eig(A) vs. svd(A), complex eigs

# random matrices are likely to give complex eigenvalues
A = np.random.randn(3,3)

print(np.sort(np.linalg.eig(A)[0]))
print(np.sort(np.linalg.svd(A)[1]))

[-0.58834196-0.34724282j -0.58834196+0.34724282j  0.26578413+0.j        ]
[0.07210863 0.67513951 2.54805189]


---
# Code Challenge: U from EigenDecomposition of A^TA
---

In [7]:
# create a matrix (3x6)
m = 3
n = 6
A = np.random.randn(m,n)

# full SVD (variables Us,Ss,Vs)
Us, Ss, Vs = np.linalg.svd(A)

# eig of A'A
L,V = np.linalg.eig(A.T@A)
# sort eigsolutions (outputs)
sidx = np.argsort(L)[::-1]
L = L[sidx]
V = V[:,sidx]

In [11]:
# confirm that V==Vs
print( np.round(Vs.T - V,2)), print(' ')
print( np.round(Vs.T + V,2))

[[-0.57 -0.13  1.81  0.12 -0.23  0.27]
 [ 1.22 -0.99  0.53 -0.72  0.48 -0.25]
 [-0.34  0.67  0.49 -0.34  0.52 -0.47]
 [-0.21 -1.4  -0.12  0.66 -0.3   0.1 ]
 [ 1.32  0.67  0.41  0.99 -0.35 -0.23]
 [ 0.53  0.34 -0.02 -0.62 -0.28  1.18]]
 
[[-0.   -0.   -0.    0.16 -0.3  -0.33]
 [ 0.    0.    0.   -0.36 -0.32  0.42]
 [-0.   -0.    0.   -0.08  1.07  1.18]
 [ 0.   -0.   -0.    0.48  1.04  0.24]
 [ 0.    0.    0.    0.04  0.77 -0.41]
 [ 0.    0.    0.    1.07 -0.39  0.54]]


In [9]:
# chech the relationship between Ss and L
print(L), print(' ')
print(Ss**2)

[ 4.60288472e+00  3.41620113e+00  1.70356386e+00  1.96848269e-16
 -6.17698515e-17 -4.44089210e-16]
 
[4.60288472 3.41620113 1.70356386]


In [13]:
# Create U using only A, V, L
U = np.zeros((m,m))
for i in range(m):
  U[:,i] = A@V[:,i].T/np.sqrt(L[i])

# confirm that U==Us
print(np.round( U-Us,2 ))


[[ 1.04 -0.29  1.68]
 [ 0.19  1.98  0.23]
 [ 1.7  -0.04 -1.06]]
