<a href="https://colab.research.google.com/github/SiracencoSerghei/linear_algebra/blob/main/2.9_Least_Squares/2.9_4_least-squares_via_QR_decompos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sympy import *
import scipy.io as sio
from mpl_toolkits.mplot3d import Axes3D
import io
import requests

---
# Code Challenge: Least-squares via QR decomposition
---

In [4]:
# generate random data
m = 10
n = 3

X = np.random.randn(m,n)
y = np.random.randn(m,1)

# QR decomposition
Q,R = np.linalg.qr(X)
beta1 = np.linalg.solve(R.T@R, (Q@R).T@y)

# compare against standart left inverse method
beta2 = np.linalg.solve(X.T@X,X.T@y)
beta3 = np.linalg.lstsq(X,y,rcond=None)[0] # basically just a wrapper for solve function

print(beta1), print(' ')
print(beta2), print(' ')
print(beta3), print(' ')


[[ 0.10885807]
 [-0.1625521 ]
 [-0.57671686]]
 
[[ 0.10885807]
 [-0.1625521 ]
 [-0.57671686]]
 
[[ 0.10885807]
 [-0.1625521 ]
 [-0.57671686]]
 


(None, None)