<a href="https://colab.research.google.com/github/SiracencoSerghei/linear_algebra/blob/main/2.9_Least_Squares/2.9_1_Least-squares.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import matplotlib.pyplot as plt
from sympy import *
import scipy.io as sio
from mpl_toolkits.mplot3d import Axes3D

---
# Least-squares via row-reduction
---


In [4]:
m = 10
n = 3

# create data
X = np.random.randn(m,n) # "design matrix"
y = np.random.randn(m,1) # "outcome measures (data)" if (m) = vector, if(m,1) = column-vector

np.shape(y)

(10, 1)

In [3]:
# try directly applying RREF
Xy = Matrix( np.concatenate([X,y],axis=1) )
print( Xy.rref() )

(Matrix([
[1, 0, 0, 0],
[0, 1, 0, 0],
[0, 0, 1, 0],
[0, 0, 0, 1],
[0, 0, 0, 0],
[0, 0, 0, 0],
[0, 0, 0, 0],
[0, 0, 0, 0],
[0, 0, 0, 0],
[0, 0, 0, 0]]), (0, 1, 2, 3))


In [6]:
# now reapply to the normal equations
XtX = X.T@X
Xty = X.T@y
normEQ = Matrix( np.concatenate( [XtX,Xty],axis=1 ) )
# axis=1 means concatenate along the columns (horizontally).

Xsol = normEQ.rref()
Xsol = Xsol[0]
beta = Xsol[:,-1]

print(np.array(Xsol)), print(' ')
print(beta), print(' ')

# compare to left-inverse
beta2 = np.linalg.inv(XtX) @ Xty
print(beta2), print(' ')

# and with the python solver
beta3 = np.linalg.solve(XtX,Xty)
print(beta3)

# for practical purposes and better performance,
#     using np.linalg.solve is generally the preferred method.

[[1 0 0 0.00879596704218501]
 [0 1 0 -0.253788293169580]
 [0 0 1 0.144693231516216]]
 
Matrix([[0.00879596704218501], [-0.253788293169580], [0.144693231516216]])
 
[[ 0.00879597]
 [-0.25378829]
 [ 0.14469323]]
 
[[ 0.00879597]
 [-0.25378829]
 [ 0.14469323]]
