<a href="https://colab.research.google.com/github/SiracencoSerghei/linear_algebra/blob/main/2.5_systems/2.5_2_RREF.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import numpy as np
import matplotlib.pyplot as plt
import math
from mpl_toolkits.mplot3d import Axes3D
from IPython import display
import time
import sympy

---
# Reduced Row Echelon Form (RREF)
---

In [12]:
# Create some random matrices using sympy
# because the numpy dosn't have method rref()
A = sympy.Matrix(np.random.randn(4, 4))
B = sympy.Matrix(np.random.randn(4, 3))

# Compute RREF
rrefA = A.rref()
rrefB = B.rref()

print(rrefA)
print(rrefB)

# Print out the matrix and its RREF
print("Original Matrix A:\n", np.array(A), "\n")
print("RREF of Matrix A:\n", np.array(rrefA[0]), "\n")

print("Original Matrix B:\n", np.array(B), "\n")
print("RREF of Matrix B:\n", np.array(rrefB[0]))

(Matrix([
[1, 0, 0, 0],
[0, 1, 0, 0],
[0, 0, 1, 0],
[0, 0, 0, 1]]), (0, 1, 2, 3))
(Matrix([
[1, 0, 0],
[0, 1, 0],
[0, 0, 1],
[0, 0, 0]]), (0, 1, 2))
Original Matrix A:
 [[0.169289581714553 -0.435651508241546 1.43571179510589 2.07334230235915]
 [0.165029685633130 -1.68008725943733 2.17874738485114 -2.34587293829419]
 [-1.35021639819015 0.804069793752352 -0.886702506907874
  0.592637717099772]
 [-0.998124301070390 1.35659595731957 1.59052837505579 1.61825041170547]] 

RREF of Matrix A:
 [[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]] 

Original Matrix B:
 [[0.0542312128087639 0.990079995437822 -0.186141941632260]
 [-1.02127487133186 -1.84624894347826 -0.0747330592052304]
 [0.195647026836827 -0.601688070335025 -0.0352025086349062]
 [-0.148236553489164 1.51703309242094 -0.297908081898847]] 

RREF of Matrix B:
 [[1 0 0]
 [0 1 0]
 [0 0 1]
 [0 0 0]]


---
# Code challenge: RREF of matricies with different sizes and ranks (of random matricies)
---

In [19]:
# square
# reqtangular (tall, wide)
# linear dependencies (on columns, rows)

# square
m = 5
n = 5
A = np.random.randn(m,n)

# Add linear dependency
A[:,0] = A[:,1]

print(np.array(sympy.Matrix(A).rref()[0]))
print(' ')
print(np.array(sympy.Matrix(A).rref()[1]))


[[1 1.00000000000000 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]
 [0 0 0 0 0]]
 
[0 2 3 4]
