In [1]:
import numpy as np

---
# Transpose
---

In [9]:
M = np.array([[1,2,3],
             [2,3,4]])
print(M), print(' ')
print(M.T), print(' ') # one transpose
print(M.T.T), print(' ') # double-transpose returns original matrix

# can also use the function transpose
print(np.transpose(M)), print(' ')
print(np.matrix(M).H)

[[1 2 3]
 [2 3 4]]
 
[[1 2]
 [2 3]
 [3 4]]
 
[[1 2 3]
 [2 3 4]]
 
[[1 2]
 [2 3]
 [3 4]]
 
[[1 2]
 [2 3]
 [3 4]]


In [7]:
# warning! be careful when using complex matrices
C = np.array([ [4+1j , 3 , 2-4j] ])

print(C), print('')
print(C.T), print('')
print(np.transpose(C)), print('')

# Note: In MATLAB, the transpose is the Hermitian transpose; 
#       in Python, you need to call the Hermitian explicitly by first converting from an array into a matrix
print(C.conjugate()), print('')
print(C.conjugate().T), print('') # note the sign flips!
print(np.matrix(C).H)


[[4.+1.j 3.+0.j 2.-4.j]]

[[4.+1.j]
 [3.+0.j]
 [2.-4.j]]

[[4.+1.j]
 [3.+0.j]
 [2.-4.j]]

[[4.-1.j 3.-0.j 2.+4.j]]

[[4.-1.j]
 [3.-0.j]
 [2.+4.j]]

[[4.-1.j]
 [3.-0.j]
 [2.+4.j]]
