---
# Diagonal and trace
---

In [1]:
import numpy as np

In [6]:

M = np.round( 5*np.random.randn(4,4) )
print(M), print(' ')
# extract the diagonals
d = np.diag(M)
print(d), print(' ')

# notice the two ways of using the diag function

d = np.diag(M) # input is matrix, output is vector
D = np.diag(d) # input is vector, output is matrix
    # This function takes the 1D array d 
    # and creates a diagonal matrix where the elements 
    # of d are placed on the main diagonal, 
    # and all other elements (off-diagonal elements) 
    # are set to zero.

  
print(d), print(' ')
print(D), print(' ')
# trace as sum of diagonal elements
tr = np.trace(M)
tr2 = sum( np.diag(M) )
print(tr,tr2)

[[ 1. -3. -2. -4.]
 [ 8. -1. -7. -4.]
 [-6. -8. -1. -1.]
 [ 4. -7. -9.  5.]]
 
[ 1. -1. -1.  5.]
 
[ 1. -1. -1.  5.]
 
[[ 1.  0.  0.  0.]
 [ 0. -1.  0.  0.]
 [ 0.  0. -1.  0.]
 [ 0.  0.  0.  5.]]
 
4.0 4.0


In [35]:
# whether the trace is linear

# tr(A) + tr(B) == tr(A+B) ???
# tr(l*A) == l * tr(A)  ???

m = 4
n = 4

A = np.random.randn(m,n)
B = np.random.randn(m,n)

l = np.random.rand()

precision = 10
trace_sum = round(np.trace(A+B), precision)
individual_sum = round(np.trace(A) + np.trace(B), precision)

print(f'tr(A+B) = {trace_sum}')
print(f'tr(A) + tr(B) = {individual_sum}')

print(f'tr(A+B) == tr(A) + tr(B) => {trace_sum == individual_sum}')
print(' ')

print(f' tr(l*A) = {np.trace(l*A)}')
print(f'l * tr(A) = {l * np.trace(A)}')

tr(A+B) = -1.2591224949
tr(A) + tr(B) = -1.2591224949
tr(A+B) == tr(A) + tr(B) => True
 
 tr(l*A) = -1.4233909815369796
l * tr(A) = -1.4233909815369798
