In [1]:
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

In [7]:
A = np.random.randn(5,4)
B = np.random.randn(5,3)
C = np.random.randn(5,4)

## try to add them
# # AB = A + B # error
# AC = A + C
# # print(AB), print(' ')
# print(AC), print(' ')

## "shifting" a matrix
l = .3 # lambda
N = 5 # size of square matrix
D = np.random.randn(N,N) # can only shift a square matrix

Ds = D + l*np.eye(N)

print(D), print(' '), print(Ds)



[[-3.03227206  0.75462626 -1.54842713 -0.1329239   1.14915098]
 [-1.50019415  0.79727018 -1.19514418 -1.96629284 -1.28300449]
 [ 0.83797252 -0.48985235  0.42898395 -1.77333565 -0.0296987 ]
 [ 1.06694995  0.45378031  1.01791103  0.97363825  1.02824268]
 [ 1.15945075  0.28429742  1.06785545  1.04798155 -0.92716093]]
 
[[-2.73227206  0.75462626 -1.54842713 -0.1329239   1.14915098]
 [-1.50019415  1.09727018 -1.19514418 -1.96629284 -1.28300449]
 [ 0.83797252 -0.48985235  0.72898395 -1.77333565 -0.0296987 ]
 [ 1.06694995  0.45378031  1.01791103  1.27363825  1.02824268]
 [ 1.15945075  0.28429742  1.06785545  1.04798155 -0.62716093]]


(None, None, None)