In [1]:
import numpy as np

---
# matrix-scalar multiplication
---

In [3]:
# define matrix and scalar
M = np.array([ [1, 2], [2, 5] ])
s = 2

# pre- and post-multiplication is the same:
print( M*s )
print( s*M )


[[ 2  4]
 [ 4 10]]
[[ 2  4]
 [ 4 10]]


In [7]:
# matrix sizes
m = 7
n = 5

# create two matrices
A = np.random.randn(m,n)
B = np.random.randn(m,n)

# scalar
s = np.random.randn()

# compute both sides of the equation
resL = s * (A+B)
resR = s*A + s*B

print(resL), print(' ')
print(resR), print(' ')
print(resL - resR)


[[-0.11040784 -0.32114107 -0.1593138  -0.22252587  0.12846379]
 [-0.14340649  0.06791943  0.49862472  0.16334734 -0.03553503]
 [ 0.05067113  0.02880223  0.08076858 -0.07514954  0.10456388]
 [-0.08428637 -0.12605724 -0.17254988 -0.1291866   0.07337697]
 [ 0.25737756  0.16964824  0.20430015 -0.04906575 -0.04884535]
 [-0.06258909  0.3614903  -0.02131677 -0.14749324  0.09847738]
 [ 0.18890325 -0.0692917  -0.25647079  0.06002271  0.1702287 ]]
 
[[-0.11040784 -0.32114107 -0.1593138  -0.22252587  0.12846379]
 [-0.14340649  0.06791943  0.49862472  0.16334734 -0.03553503]
 [ 0.05067113  0.02880223  0.08076858 -0.07514954  0.10456388]
 [-0.08428637 -0.12605724 -0.17254988 -0.1291866   0.07337697]
 [ 0.25737756  0.16964824  0.20430015 -0.04906575 -0.04884535]
 [-0.06258909  0.3614903  -0.02131677 -0.14749324  0.09847738]
 [ 0.18890325 -0.0692917  -0.25647079  0.06002271  0.1702287 ]]
 
[[ 0.00000000e+00  5.55111512e-17  2.77555756e-17  0.00000000e+00
   0.00000000e+00]
 [ 0.00000000e+00  0.000000