In [5]:
import numpy as np

In [ ]:
# A zoo of matrices

In [15]:
## square vs rectangular
S = np.random.randn(5, 5)
R = np.random.randn(5, 2) # 5 rows, 2 columns
# print(S), print(' ')
# print(R)

## identity
# I = np.eye(3)
# print(I), print(' ')

## zeros
# Z = np.zeros((4,4))
# print(Z), print(' ')

## diagonal
# D = np.diag([1, 2, 3, 5, 2])
# print(D), print(' ')

## create triangular matrix from full matricies
# U = np.triu(S)
# L = np.tril(S)
# print(U), print(' ')
# print(L), print(' ')

## concatenate matricies (sizes must match!!!)
A = np.random.randn(3, 2)
B = np.random.randn(3, 4)
C = np.concatenate((A, B), axis=1)
print(A), print(' ')
print(B), print(' ')
print(C), print(' ')

[[-0.35128287  1.57114037]
 [-0.75125105 -0.12921057]
 [-0.71172998  0.60481509]]
 
[[ 0.59901172  0.87469648  0.33979276 -0.52366257]
 [-1.02601636 -0.21927848  2.02392343 -0.16374359]
 [ 2.12246596  0.1002855  -0.49651671  0.04796226]]
 
[[-0.35128287  1.57114037  0.59901172  0.87469648  0.33979276 -0.52366257]
 [-0.75125105 -0.12921057 -1.02601636 -0.21927848  2.02392343 -0.16374359]
 [-0.71172998  0.60481509  2.12246596  0.1002855  -0.49651671  0.04796226]]
 


(None, None)