<a href="https://colab.research.google.com/github/SiracencoSerghei/linear_algebra/blob/main/2.7_inverse/2.7_4_inverse_diagonal_matrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
from sympy import *
import matplotlib.pyplot as plt

---
# Code Challenge: inverse of a diagonal matrix
---

In [4]:
# diagonal matricies and their inverses

# create diagonal matricies. start with 2x2
# compute their inverses

A = np.array([[2,0],[0,3]])
B = np.diag(np.arange(1,6))

print(A), print(' ')
print(np.linalg.inv(A))

print(B), print(' ')
print(np.linalg.inv(B))


[[2 0]
 [0 3]]
 
[[0.5        0.        ]
 [0.         0.33333333]]
[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]
 
[[1.         0.         0.         0.         0.        ]
 [0.         0.5        0.         0.         0.        ]
 [0.         0.         0.33333333 0.         0.        ]
 [0.         0.         0.         0.25       0.        ]
 [0.         0.         0.         0.         0.2       ]]
