<a href="https://colab.research.google.com/github/SiracencoSerghei/linear_algebra/blob/main/2.7_inverse/2.7_2_MCA_algorithm.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
from sympy import *
import matplotlib.pyplot as plt

---
# Code challenge: Implement the MCA algorithm!
---

In [10]:
# MCA algorithm in code !!!
# then compute using inv() and compare to MCA

# Step 1: Define the size of the matrix and generate a random matrix A
m = 4  # The matrix is m x m (4x4 in this case)
A = np.random.randn(m, m)  # Generate a random 4x4 matrix with elements from a normal distribution
print(A), print(' ')

# Step 2: Initialize matrices to store the minors and the cofactor signs
minors = np.zeros((m, m))  # Matrix to store the minors of A, initially filled with zeros
H = np.zeros((m, m))       # Matrix to store the signs for the cofactors, also initially filled with zeros

# Step 3: Compute the minors and the cofactor signs
for i in range(m):        # Loop over each row of the matrix A
  for j in range(m):      # Loop over each column of the matrix A

    # Create boolean arrays to select rows and columns
    rows = [True] * m     # Initialize an array to select all rows
    rows[i] = False       # Exclude the i-th row by setting it to False

    cols = [True] * m     # Initialize an array to select all columns
    cols[j] = False       # Exclude the j-th column by setting it to False

    # Compute the determinant of the submatrix obtained by removing the i-th row and j-th column
    minors[i, j] = np.linalg.det(A[rows, :][:, cols])

    # Compute the sign for the cofactor (alternating signs pattern)
    H[i, j] = (-1)**(i + j)

print(f'{minors = }')
print(f'{H = }'), print(' ')
# Step 4: Compute the cofactor matrix by multiplying the minors by their corresponding signs
C = H * minors

# Step 5: Compute the adjugate matrix by taking the transpose of the cofactor matrix
Ainv = C.T / np.linalg.det(A)  # The inverse is the adjugate divided by the determinant of A
print(A @ Ainv), print(' ')    # Print the product of A and its inverse (should be close to the identity matrix)

# Step 6: Compare the result with the built-in numpy function for matrix inversion
Ainv2 = np.linalg.inv(A)       # Compute the inverse using numpy's built-in function
print(Ainv - Ainv2), print(' ')  # Print the difference between the MCA result and the numpy result (should be close to zero)


[[ 0.38616297  0.11794826 -1.20230561 -1.33759176]
 [-0.01294222  1.71616001  0.71537203  1.38241836]
 [ 1.54894518 -0.47103238  1.31689363 -0.19900032]
 [-1.96678201 -0.27018357  1.50302551  1.00558609]]
 
minors = array([[ 2.67639425,  5.94365447, -3.8538112 , -9.39788543],
       [ 0.02839986, -4.54945624,  1.45772444,  0.90091976],
       [-1.34504122,  0.87279355, -4.02797003, -3.15529858],
       [-3.33290186, -1.82442618,  3.91931476,  4.3242413 ]])
H = array([[ 1., -1.,  1., -1.],
       [-1.,  1., -1.,  1.],
       [ 1., -1.,  1., -1.],
       [-1.,  1., -1.,  1.]])
 
[[ 1.00000000e+00 -2.53183694e-17 -2.69844999e-17  1.13866281e-16]
 [-7.23679149e-16  1.00000000e+00  3.48920681e-17 -4.97229969e-17]
 [ 2.10156855e-16  6.07029633e-18  1.00000000e+00  1.51759167e-16]
 [-5.14476674e-16  1.02505296e-17  9.44493001e-17  1.00000000e+00]]
 
[[ 5.55111512e-17  1.08420217e-17 -5.55111512e-17  1.11022302e-16]
 [-4.44089210e-16 -1.11022302e-16  0.00000000e+00 -1.11022302e-16]
 [-2.220446

(None, None)